-- MySQL Script generated by MySQL Workbench
-- Tue Aug 25 13:50:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bodega
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bodega
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bodega` DEFAULT CHARACTER SET utf8 ;
USE `Bodega` ;

-- -----------------------------------------------------
-- Table `Bodega`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega`.`CLIENTE` (
  `ID_CLIENTE` INT NOT NULL,
  `NOMBRE` VARCHAR(50) NULL,
  `APELLIDO` VARCHAR(50) NULL,
  `DIRECCION` VARCHAR(25) NULL,
  `TELEFONO` INT NULL,
  `NIT` INT NULL,
  PRIMARY KEY (`ID_CLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega`.`PROVEEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega`.`PROVEEDOR` (
  `ID_PROVEEDOR` INT NOT NULL,
  `NOMBRE_PROVEEDOR` VARCHAR(50) NULL,
  `APELLIDO_PROVEEDOR` VARCHAR(50) NULL,
  `TELEFONO` VARCHAR(13) NULL,
  `CORREO` VARCHAR(25) NULL,
  `DIRECCION` VARCHAR(25) NULL,
  PRIMARY KEY (`ID_PROVEEDOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega`.`ENCABEZADO_COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega`.`ENCABEZADO_COMPRA` (
  `ID_ENCABEZADO_COMPRA` INT NOT NULL,
  `ID_EMPLEADO_FK` INT NULL,
  `ID_PROVEEDOR_FK` INT NULL,
  `FECHA_COMPRA` VARCHAR(25) NULL,
  `TOTAL_COMPRA` DOUBLE NULL,
  PRIMARY KEY (`ID_ENCABEZADO_COMPRA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega`.`DETALLE_COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega`.`DETALLE_COMPRA` (
  `ID_DETALLE_COMPRA` INT NOT NULL,
  `ID_PRODUCTO_FK` INT NULL,
  `DESCRIPCION` VARCHAR(125) NULL,
  `CANTIDAD` INT NULL,
  `PRECIO_UNIDAD` DOUBLE NULL,
  `SUBTOTAL` DOUBLE NULL,
  PRIMARY KEY (`ID_DETALLE_COMPRA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega`.`INVENTARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega`.`INVENTARIO` (
  `ID_PRODUCTO` INT NOT NULL,
  `NOMBRE_PRODUCTO` VARCHAR(50) NULL,
  `EXISTENCIA` INT NULL,
  `PRECIO` DOUBLE NULL,
  `DESCRIPCION` VARCHAR(125) NULL,
  `ID_ESTADO_PRODUCTO` INT NULL,
  PRIMARY KEY (`ID_PRODUCTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega`.`EMPLEADO` (
  `ID_EMPLEADO` INT NOT NULL,
  `NOMBRE` VARCHAR(50) NULL,
  `APELLIDO` VARCHAR(50) NULL,
  `TELEFONO` VARCHAR(13) NULL,
  `ID_PUESTO_FK` INT NULL,
  `ID_ESTADO_EMPLEADO_FK` INT NULL,
  PRIMARY KEY (`ID_EMPLEADO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega`.`VENTA_ENCABEZADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega`.`VENTA_ENCABEZADO` (
  `ID_VENTA_ENCABEZADO` INT NOT NULL,
  `ID_EMPLEADO_FK` INT NULL,
  `ID_CLIENTE_FK` INT NULL,
  `FECHA_VENTA` VARCHAR(15) NULL,
  `TOTAL_VENTA` DOUBLE NULL,
  PRIMARY KEY (`ID_VENTA_ENCABEZADO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega`.`DETALLE_VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega`.`DETALLE_VENTA` (
  `ID_DETALLE_VENTA` INT NOT NULL,
  `ID_PRODUCTO_FK` INT NULL,
  `DESCRIPCION` VARCHAR(125) NULL,
  `CANTIDAD` INT NULL,
  `PRECIO_UNITARIO` DOUBLE NULL,
  `SUB_TOTAL` DOUBLE NULL,
  PRIMARY KEY (`ID_DETALLE_VENTA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega`.`ESTADO_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega`.`ESTADO_PRODUCTO` (
  `ID_ESTADO_PRODUCTO` INT NOT NULL,
  `NOMBRE_ESTADO` VARCHAR(50) NULL,
  PRIMARY KEY (`ID_ESTADO_PRODUCTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega`.`TIPO_PUESTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega`.`TIPO_PUESTO` (
  `ID_TIPO_PUESTO` INT NOT NULL,
  `NOMBRE_PUESTO` VARCHAR(50) NULL,
  PRIMARY KEY (`ID_TIPO_PUESTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bodega`.`ESTADO_EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bodega`.`ESTADO_EMPLEADO` (
  `ID_ESTADO_EMPLEADO` INT NOT NULL,
  `NOMBRE_ESTADO` VARCHAR(50) NULL,
  PRIMARY KEY (`ID_ESTADO_EMPLEADO`))
ENGINE = InnoDB;


ALTER TABLE `DETALLE_COMPRA` 
ADD KEY `FK_DCOMPRA_PRODUCTO` (`ID_PRODUCTO_FK`);

ALTER TABLE `DETALLE_VENTA` 
ADD KEY `FK_DVENTA_PRODUCTO` (`ID_PRODUCTO_FK`);

ALTER TABLE `EMPLEADO` 
ADD KEY `FK_EMPLEADO_PUESTO` (`ID_PUESTO_FK`),
ADD KEY `FK_EMPLEADO_ESTADO` (`ID_ESTADO_EMPLEADO_FK`);

ALTER TABLE `ENCABEZADO_COMPRA` 
ADD KEY `FK_ENCABEZADO_EMPLEADO` (`ID_EMPLEADO_FK`),
ADD KEY `FK_ENCABEZADO_PROVEEDOR` (`ID_PROVEEDOR_FK`);

ALTER TABLE `INVENTARIO` 
ADD KEY `FK_INVENTARIO_ESTADO` (`ID_ESTADO_PRODUCTO`);

ALTER TABLE `VENTA_ENCABEZADO` 
ADD KEY `FK_VENTA_EMPLEADO` (`ID_EMPLEADO_FK`),
ADD KEY `FK_VENTA_CLIENTE` (`ID_CLIENTE_FK`);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
